# Generated by Django 3.0.6 on 2020-05-31 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='githublink',
            field=models.URLField(blank=True, help_text='Link your Github page here (if you have one)'),
        ),
        migrations.AddField(
            model_name='snippet',
            name='githubusername',
            field=models.CharField(blank=True, help_text='Enter your Github Username here (if you have one)', max_length=50),
        ),
        migrations.AddField(
            model_name='snippet',
            name='languages',
            field=models.CharField(blank=True, choices=[('python', 'Python'), ('c', 'C'), ('java', 'JAVA'), ('javascript', 'Javascript'), ('c++', 'C++'), ('ruby', 'Ruby'), ('csharp', 'C#'), ('brainfuck', 'BrainFuck')], max_length=200),
        ),
        migrations.AddField(
            model_name='snippet',
            name='rollno',
            field=models.CharField(default='XXAG1A0XXX', max_length=10),
        ),
        migrations.AddField(
            model_name='snippet',
            name='sec',
            field=models.CharField(default='NA', max_length=5),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='body',
            field=models.TextField(blank=True, default='NA', help_text='Any Queries?'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='email',
            field=models.EmailField(blank=True, default='abc@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='name',
            field=models.CharField(help_text='Enter your name here ', max_length=100),
        ),
    ]
