# Generated by Django 3.0.6 on 2020-05-31 08:38

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20200531_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='phoneno',
            field=phone_field.models.PhoneField(blank=True, max_length=31),
        ),
    ]
