# Generated by Django 3.0.6 on 2020-05-31 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_snippet_phoneno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='body',
            field=models.TextField(blank=True, default='Any Queries?'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='email',
            field=models.EmailField(blank=True, default='YourName@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='name',
            field=models.CharField(help_text='Enter your name here', max_length=100),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='sec',
            field=models.CharField(default='II-ECE-B', max_length=10),
        ),
    ]
