# Generated by Django 3.0.6 on 2020-05-31 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_auto_20200531_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='sec',
            new_name='Class YEAR : BRANCH : SECTION',
        ),
        migrations.RenameField(
            model_name='snippet',
            old_name='email',
            new_name='EMAIL',
        ),
        migrations.RenameField(
            model_name='snippet',
            old_name='githublink',
            new_name='Github Profile',
        ),
        migrations.RenameField(
            model_name='snippet',
            old_name='githubusername',
            new_name='Github Username',
        ),
        migrations.RenameField(
            model_name='snippet',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='snippet',
            old_name='phoneno',
            new_name='Phone No',
        ),
        migrations.RenameField(
            model_name='snippet',
            old_name='languages',
            new_name='Preferred Language',
        ),
        migrations.RenameField(
            model_name='snippet',
            old_name='rollno',
            new_name='Roll No',
        ),
        migrations.RenameField(
            model_name='snippet',
            old_name='body',
            new_name='Suggestion',
        ),
    ]
