# Generated by Django 3.0.6 on 2020-05-31 11:58

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_auto_20200531_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='Class YEAR : BRANCH : SECTION',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='EMAIL',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='Github Profile',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='Github Username',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='Phone No',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='Preferred Language',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='Roll No',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='Suggestion',
        ),
        migrations.AddField(
            model_name='snippet',
            name='body',
            field=models.TextField(blank=True, default='Any Queries?', verbose_name='Suggestion'),
        ),
        migrations.AddField(
            model_name='snippet',
            name='email',
            field=models.EmailField(blank=True, default='YourName@example.com', max_length=254, verbose_name='EMAIL'),
        ),
        migrations.AddField(
            model_name='snippet',
            name='githublink',
            field=models.URLField(blank=True, help_text='Link your Github page here (if you have one)', verbose_name='Github Profile'),
        ),
        migrations.AddField(
            model_name='snippet',
            name='githubusername',
            field=models.CharField(blank=True, help_text='Enter your Github Username here (if you have one)', max_length=50, verbose_name='Github Username'),
        ),
        migrations.AddField(
            model_name='snippet',
            name='languages',
            field=models.CharField(blank=True, choices=[('python', 'Python'), ('c', 'C'), ('java', 'JAVA'), ('javascript', 'Javascript'), ('c++', 'C++'), ('ruby', 'Ruby'), ('csharp', 'C#'), ('brainfuck', 'BrainFuck')], max_length=200, verbose_name='Preferred Language'),
        ),
        migrations.AddField(
            model_name='snippet',
            name='name',
            field=models.CharField(default='None', max_length=100, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='snippet',
            name='phoneno',
            field=phone_field.models.PhoneField(blank=True, max_length=31, verbose_name='Phone No'),
        ),
        migrations.AddField(
            model_name='snippet',
            name='rollno',
            field=models.CharField(default='XXAG1A0XXX', max_length=10, verbose_name='Roll No'),
        ),
        migrations.AddField(
            model_name='snippet',
            name='sec',
            field=models.CharField(default='II-ECE-B', max_length=10, verbose_name='Class YEAR : BRANCH : SECTION'),
        ),
    ]
