# Generated by Django 3.0.6 on 2020-05-31 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_auto_20200531_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='user_ip',
            field=models.GenericIPAddressField(default='169.254.162.160'),
        ),
    ]
