# Generated by Django 3.0.6 on 2020-05-31 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0007_snippet_user_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='email',
            field=models.EmailField(blank=True, default=' ', max_length=254, verbose_name='EMAIL'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='rollno',
            field=models.CharField(max_length=10, verbose_name='Roll No'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='sec',
            field=models.CharField(max_length=10, verbose_name='Class'),
        ),
    ]
