# Generated by Django 3.0.6 on 2020-05-31 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0008_auto_20200531_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='githublink',
            field=models.URLField(blank=True, verbose_name='Github Profile'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='githubusername',
            field=models.CharField(blank=True, max_length=50, verbose_name='Github Username'),
        ),
    ]
