# Generated by Django 3.0.6 on 2020-06-01 11:02

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0010_auto_20200601_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='body',
            field=models.TextField(blank=True, help_text='I would love to ...', verbose_name='Why do you want to join'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='email',
            field=models.EmailField(blank=True, default=' ', help_text='senpai.awesome@kawaii.jp', max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='languages',
            field=models.CharField(blank=True, choices=[('python', 'Python'), ('c', 'C'), ('c++', 'C++'), ('csharp', 'C#'), ('java', 'JAVA'), ('javascript', 'Javascript'), ('ruby', 'Ruby'), ('assembly', 'Assembly'), ('brainfuck', 'BrainFuck'), ('cobol', 'COBOL'), ('fotran', 'FOTRAN'), ('pascal', 'Pascal'), ('php', 'PHP'), ('basic', 'BASIC'), ('other', 'Other')], default='other', max_length=200, verbose_name='Preferred Language'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='phoneno',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
