# Generated by Django 3.0.6 on 2020-06-02 11:49

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0011_auto_20200601_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='animepage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op', models.CharField(blank=True, max_length=100, verbose_name='きみ の な わ [ Nāmayē ]')),
                ('anime_name', models.CharField(blank=True, max_length=300, verbose_name='すきわ あにめ [ Favorite anime ]')),
            ],
        ),
        migrations.AlterField(
            model_name='snippet',
            name='phoneno',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='+919876543210', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='user_ip',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
    ]
